// Цвета для золотых частиц
export const GOLD_COLORS = [
  '#FFD700', // Золотой
  '#FFC125', // Насыщенный золотой
  '#FFCC33', // Яркий золотой
  '#E6BE8A', // Песочный золотой
  '#DAA520'  // Тёмный золотой
];

export const COLORS = {
  "White smoke":"#efefed",
  "Alabaster":"#ebe3d8",
  "Light yellow":"#ffffe3",
  "Melon":"#FFB096",
  "Tomato":"#ff6048",
  "Cinnabar":"#db5f43",
  "Cornell red":"#af1510",
  "Eerie black":"#1d1b1c",
  "Gunmetal":"#2e3439"
}

// Country names from the geoJSON data
export const COUNTRY_NAMES = [
  'Afghanistan',
  'Angola',
  'Albania',
  'United Arab Emirates',
  'Argentina',
  'Armenia',
  'Antarctica',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Burundi',
  'Belgium',
  'Benin',
  'Burkina Faso',
  'Bangladesh',
  'Bulgaria',
  'Bahamas',
  'Bosnia and Herzegovina',
  'Belarus',
  'Belize',
  'Bolivia',
  'Brazil',
  'Brunei',
  'Bhutan',
  'Botswana',
  'Central African Republic',
  'Canada',
  'Switzerland',
  'Chile',
  'China',
  'Ivory Coast',
  'Cameroon',
  'Democratic Republic of the Congo',
  'Republic of the Congo',
  'Colombia',
  'Costa Rica',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Germany',
  'Djibouti',
  'Denmark',
  'Dominican Republic',
  'Algeria',
  'Ecuador',
  'Egypt',
  'Eritrea',
  'Spain',
  'Estonia',
  'Ethiopia',
  'Finland',
  'Fiji',
  'Falkland Islands',
  'France',
  'Gabon',
  'United Kingdom',
  'Georgia',
  'Ghana',
  'Guinea',
  'Gambia',
  'Guinea-Bissau',
  'Equatorial Guinea',
  'Greece',
  'Greenland',
  'Guatemala',
  'Guyana',
  'Honduras',
  'Croatia',
  'Haiti',
  'Hungary',
  'Indonesia',
  'India',
  'Ireland',
  'Iran',
  'Iraq',
  'Iceland',
  'Israel',
  'Italy',
  'Jamaica',
  'Jordan',
  'Japan',
  'Kazakhstan',
  'Kenya',
  'Kyrgyzstan',
  'Cambodia',
  'South Korea',
  'Kosovo',
  'Kuwait',
  'Laos',
  'Lebanon',
  'Liberia',
  'Libya',
  'Sri Lanka',
  'Lesotho',
  'Lithuania',
  'Luxembourg',
  'Latvia',
  'Morocco',
  'Moldova',
  'Madagascar',
  'Mexico',
  'Macedonia',
  'Mali',
  'Myanmar',
  'Montenegro',
  'Mongolia',
  'Mozambique',
  'Mauritania',
  'Malawi',
  'Malaysia',
  'Namibia',
  'New Caledonia',
  'Niger',
  'Nigeria',
  'Nicaragua',
  'Netherlands',
  'Norway',
  'Nepal',
  'New Zealand',
  'Oman',
  'Pakistan',
  'Panama',
  'Peru',
  'Philippines',
  'Papua New Guinea',
  'Poland',
  'Puerto Rico',
  'North Korea',
  'Portugal',
  'Paraguay',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Western Sahara',
  'Saudi Arabia',
  'Sudan',
  'South Sudan',
  'Senegal',
  'Solomon Islands',
  'Sierra Leone',
  'El Salvador',
  'Somalia',
  'Serbia',
  'Suriname',
  'Slovakia',
  'Slovenia',
  'Sweden',
  'Swaziland',
  'Syria',
  'Chad',
  'Togo',
  'Thailand',
  'Tajikistan',
  'Turkmenistan',
  'East Timor',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Taiwan',
  'Tanzania',
  'Uganda',
  'Ukraine',
  'Uruguay',
  'United States',
  'Uzbekistan',
  'Venezuela',
  'Vietnam',
  'Vanuatu',
  'Yemen',
  'South Africa',
  'Zambia',
  'Zimbabwe'
];
